I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1216, in script
    makhluk_1 "Tidak juga"
Exception: Sayer 'makhluk_1' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1216, in script
    makhluk_1 "Tidak juga"
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\ast.py", line 2572, in execute
    Say.execute(self)
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'makhluk_1' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.0.24082114
 
Sun Dec  8 18:35:51 2024
