I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 13, in script
    "[larasati_story_2.count()]"
TypeError: list.count() takes exactly one argument (0 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 13, in script
    "[larasati_story_2.count()]"
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\ast.py", line 2572, in execute
    Say.execute(self)
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\ast.py", line 615, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\exports\sayexports.py", line 132, in say
    who(what, *args, **kwargs)
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\character.py", line 1436, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\character.py", line 1350, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\character.py", line 1330, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\substitutions.py", line 373, in substitute
    s = interpolate(s, variables) # type: ignore
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\substitutions.py", line 86, in interpolate
    raise e
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\substitutions.py", line 78, in interpolate
    value = renpy.python.py_eval(code, {}, scope)
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
TypeError: list.count() takes exactly one argument (0 given)

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.0.24082114
 
Sat Nov 30 23:53:36 2024
